
version: '3.8'

services:
  pothole-detection:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPTIMIZATION_LEVEL=speed
      - GPU_ACCELERATION=true
    volumes:
      - ./models:/app/models
      - ./results:/app/results
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pothole-detection
    deploy:
      replicas: 1

  monitoring:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
networks:
  pothole-network:
    driver: bridge
