
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pothole-detection
  labels:
    app: pothole-detection
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pothole-detection
  template:
    metadata:
      labels:
        app: pothole-detection
    spec:
      containers:
      - name: pothole-detection
        image: ultimate-pothole-detection:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPTIMIZATION_LEVEL
          value: "speed"
        - name: GPU_ACCELERATION
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pothole-detection-service
spec:
  selector:
    app: pothole-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
